import type { Metadata } from "next";
import { Inter, JetBrains_Mono, Geist } from "next/font/google";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn(inter.variable, jetbrainsMono.variable, "font-sans", geist.variable)}>
      <body>
        <style>{`
          body {
            font-family: var(--font-inter), Arial, Helvetica, sans-serif;
            margin: 0;
          }

          h1, h2, h3, h4, h5, h6 {
            font-family: var(--font-inter), Arial, Helvetica, sans-serif;
            font-weight: 700;
          }

          pre, code {
            font-family: var(--font-jetbrains-mono), monospace;
          }
        `}</style>
        {children}
      </body>
    </html>
  );
}
